GET http://localhost:3000/users
###

GET http://localhost:3000/user/1
###

POST http://localhost:3000/user
Content-Type: application/json

{
  "fisrtname": "John",
  "lastname": "Lark",
  "email": "johnlark@gmail.com"
}
###

DELETE http://localhost:3000/user/1
###

PUT http://localhost:3000/user/2
Content-Type: application/json

{
  "fisrtname": "John1",
  "lastname": "Lark",
  "email": "johnlark@gmail.com"
}
###